begin;

create table if not exists public.schedule_closure (
  id bigint generated by default as identity primary key,
  branch_id bigint null references public.branch(id) on delete cascade,
  starts_on date not null,
  ends_on date not null,
  reason text null,
  is_active boolean not null default true,
  created_by bigint null references public."user"(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint schedule_closure_dates_check check (starts_on <= ends_on),
  constraint schedule_closure_reason_length_check check (reason is null or char_length(reason) <= 120)
);

create index if not exists schedule_closure_active_dates_idx
  on public.schedule_closure (starts_on, ends_on, branch_id)
  where is_active = true;

alter table public.class_schedule
  add column if not exists closure_id bigint null
  references public.schedule_closure(id) on delete set null;

alter table public.class_schedule
  add column if not exists is_manual_override boolean not null default false;

create index if not exists class_schedule_closure_id_idx
  on public.class_schedule (closure_id)
  where closure_id is not null;

alter table public.schedule_closure enable row level security;

drop policy if exists "Head coaches can read schedule closures" on public.schedule_closure;
create policy "Head coaches can read schedule closures"
  on public.schedule_closure
  for select
  to authenticated
  using (
    exists (
      select 1
      from public."user" as app_user
      where app_user.auth_id = auth.uid()
        and app_user.role = 'head_coach'
    )
  );

revoke all on table public.schedule_closure from anon, authenticated, public;
grant select on public.schedule_closure to authenticated;
grant all on public.schedule_closure to service_role;
revoke all on sequence public.schedule_closure_id_seq from anon, authenticated, public;
grant usage, select on sequence public.schedule_closure_id_seq to service_role;

commit;
