begin;

create table if not exists public.schedule_absence_report (
  id bigint generated by default as identity primary key,
  coach_id bigint not null references public."user"(id) on delete cascade,
  starts_on date not null,
  ends_on date not null,
  reason text null,
  status text not null default 'pending',
  resolution text null,
  substitute_coach_id bigint null references public."user"(id) on delete set null,
  created_at timestamptz not null default now(),
  resolved_by bigint null references public."user"(id) on delete set null,
  resolved_at timestamptz null,
  constraint schedule_absence_report_dates_check check (starts_on <= ends_on),
  constraint schedule_absence_report_reason_length_check check (reason is null or char_length(reason) <= 200),
  constraint schedule_absence_report_status_check check (status in ('pending', 'resolved')),
  constraint schedule_absence_report_resolution_check check (resolution is null or resolution in ('covered', 'cancelled', 'no_sessions')),
  constraint schedule_absence_report_resolution_state_check check (
    (status = 'pending' and resolution is null and resolved_at is null)
    or (status = 'resolved' and resolution is not null and resolved_at is not null)
  )
);

create index if not exists schedule_absence_report_pending_dates_idx
  on public.schedule_absence_report (starts_on, ends_on, created_at desc)
  where status = 'pending';

create index if not exists schedule_absence_report_coach_dates_idx
  on public.schedule_absence_report (coach_id, starts_on, ends_on, created_at desc);

alter table public.class_schedule
  add column if not exists absence_report_id bigint null
  references public.schedule_absence_report(id) on delete set null;

create index if not exists class_schedule_absence_report_id_idx
  on public.class_schedule (absence_report_id)
  where absence_report_id is not null;

alter table public.schedule_absence_report enable row level security;

drop policy if exists "Coaches can read their absence reports" on public.schedule_absence_report;
create policy "Coaches can read their absence reports"
  on public.schedule_absence_report
  for select
  to authenticated
  using (
    coach_id = (
      select app_user.id
      from public."user" as app_user
      where app_user.auth_id = auth.uid()
    )
  );

drop policy if exists "Head coaches can read all absence reports" on public.schedule_absence_report;
create policy "Head coaches can read all absence reports"
  on public.schedule_absence_report
  for select
  to authenticated
  using (
    exists (
      select 1
      from public."user" as app_user
      where app_user.auth_id = auth.uid()
        and app_user.role = 'head_coach'
    )
  );

revoke all on table public.schedule_absence_report from anon, authenticated, public;
grant select on public.schedule_absence_report to authenticated;
grant all on public.schedule_absence_report to service_role;
revoke all on sequence public.schedule_absence_report_id_seq from anon, authenticated, public;
grant usage, select on sequence public.schedule_absence_report_id_seq to service_role;

commit;
